/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectTasksRouteImport } from './routes/project-tasks'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AcademicRouteImport } from './routes/academic'
import { Route as IndexRouteImport } from './routes/index'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectTasksRoute = ProjectTasksRouteImport.update({
  id: '/project-tasks',
  path: '/project-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicRoute = AcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic': typeof AcademicRoute
  '/archive': typeof ArchiveRoute
  '/assignments': typeof AssignmentsRoute
  '/calendar': typeof CalendarRoute
  '/career': typeof CareerRoute
  '/focus': typeof FocusRoute
  '/ideas': typeof IdeasRoute
  '/knowledge': typeof KnowledgeRoute
  '/notifications': typeof NotificationsRoute
  '/project-tasks': typeof ProjectTasksRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/study': typeof StudyRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic': typeof AcademicRoute
  '/archive': typeof ArchiveRoute
  '/assignments': typeof AssignmentsRoute
  '/calendar': typeof CalendarRoute
  '/career': typeof CareerRoute
  '/focus': typeof FocusRoute
  '/ideas': typeof IdeasRoute
  '/knowledge': typeof KnowledgeRoute
  '/notifications': typeof NotificationsRoute
  '/project-tasks': typeof ProjectTasksRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/study': typeof StudyRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic': typeof AcademicRoute
  '/archive': typeof ArchiveRoute
  '/assignments': typeof AssignmentsRoute
  '/calendar': typeof CalendarRoute
  '/career': typeof CareerRoute
  '/focus': typeof FocusRoute
  '/ideas': typeof IdeasRoute
  '/knowledge': typeof KnowledgeRoute
  '/notifications': typeof NotificationsRoute
  '/project-tasks': typeof ProjectTasksRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/study': typeof StudyRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic'
    | '/archive'
    | '/assignments'
    | '/calendar'
    | '/career'
    | '/focus'
    | '/ideas'
    | '/knowledge'
    | '/notifications'
    | '/project-tasks'
    | '/projects'
    | '/settings'
    | '/study'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic'
    | '/archive'
    | '/assignments'
    | '/calendar'
    | '/career'
    | '/focus'
    | '/ideas'
    | '/knowledge'
    | '/notifications'
    | '/project-tasks'
    | '/projects'
    | '/settings'
    | '/study'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/academic'
    | '/archive'
    | '/assignments'
    | '/calendar'
    | '/career'
    | '/focus'
    | '/ideas'
    | '/knowledge'
    | '/notifications'
    | '/project-tasks'
    | '/projects'
    | '/settings'
    | '/study'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicRoute: typeof AcademicRoute
  ArchiveRoute: typeof ArchiveRoute
  AssignmentsRoute: typeof AssignmentsRoute
  CalendarRoute: typeof CalendarRoute
  CareerRoute: typeof CareerRoute
  FocusRoute: typeof FocusRoute
  IdeasRoute: typeof IdeasRoute
  KnowledgeRoute: typeof KnowledgeRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectTasksRoute: typeof ProjectTasksRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  StudyRoute: typeof StudyRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-tasks': {
      id: '/project-tasks'
      path: '/project-tasks'
      fullPath: '/project-tasks'
      preLoaderRoute: typeof ProjectTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic': {
      id: '/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof AcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicRoute: AcademicRoute,
  ArchiveRoute: ArchiveRoute,
  AssignmentsRoute: AssignmentsRoute,
  CalendarRoute: CalendarRoute,
  CareerRoute: CareerRoute,
  FocusRoute: FocusRoute,
  IdeasRoute: IdeasRoute,
  KnowledgeRoute: KnowledgeRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectTasksRoute: ProjectTasksRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  StudyRoute: StudyRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
